apiVersion: apps/v1
kind: Deployment
metadata:
  name: pci-backend
  labels:
    app: pci-backend
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pci-backend
      component: backend
  template:
    metadata:
      labels:
        app: pci-backend
        component: backend
    spec:
      containers:
      - name: pci-backend
        image: pcistaging.azurecr.io/pci-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: pci-backend-secrets
              key: database-url
        - name: PORT
          value: "3000"
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: pci-backend-config
              key: cors-origin
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: pci-uploads-pvc
      imagePullSecrets:
      - name: acr-secret
