apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pci-uploads-pvc
  labels:
    app: pci-backend
    component: storage
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 20Gi
