apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yaml
- backend-service.yaml
- backend-configmap.yaml
- backend-pvc.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- frontend-configmap.yaml
- postgres-statefulset.yaml
- postgres-service.yaml
- postgres-init-configmap.yaml
- ingress.yaml
