name: Verify GitHub Secrets

on:
  workflow_dispatch:

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Check if required secrets exist
      run: |
        echo "Checking GitHub Secrets configuration..."
        
        # Check Azure credentials
        if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
          echo "❌ AZURE_CREDENTIALS secret is missing"
          exit 1
        else
          echo "✅ AZURE_CREDENTIALS secret exists"
        fi
        
        # Check database secrets  
        if [ -z "${{ secrets.POSTGRES_USER }}" ]; then
          echo "❌ POSTGRES_USER secret is missing"
        else
          echo "✅ POSTGRES_USER secret exists"
        fi
        
        if [ -z "${{ secrets.POSTGRES_PASSWORD }}" ]; then
          echo "❌ POSTGRES_PASSWORD secret is missing"
        else
          echo "✅ POSTGRES_PASSWORD secret exists"
        fi
        
        if [ -z "${{ secrets.DATABASE_URL }}" ]; then
          echo "❌ DATABASE_URL secret is missing"
        else
          echo "✅ DATABASE_URL secret exists"
        fi
        
        if [ -z "${{ secrets.NEXTAUTH_SECRET }}" ]; then
          echo "❌ NEXTAUTH_SECRET secret is missing"
        else
          echo "✅ NEXTAUTH_SECRET secret exists"
        fi
        
        echo ""
        echo "🏅 Paralympic Committee of India CI/CD Setup Check Complete!"
