apiVersion: apps/v1
kind: Deployment
metadata:
  name: pci-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: pci-frontend
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "staging"
